version: '3'

services:
  jira-mcp-server:
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - JIRA_HOST=${JIRA_HOST}
      - JIRA_USERNAME=${JIRA_USERNAME}
      - JIRA_API_TOKEN=${JIRA_API_TOKEN}
      - JIRA_PROJECT_KEY=${JIRA_PROJECT_KEY}
      - JIRA_ORGANIZATION=${JIRA_ORGANIZATION}
      - JIRA_ORGANIZATION_KEY=${JIRA_ORGANIZATION_KEY}
    env_file:
      - .env
    restart: unless-stopped
